-- Columnas g_users que faltaban en app_user (special access, prefs, T&C, media).
ALTER TABLE app_user
  ADD COLUMN hierarchy_special_access_zc text DEFAULT NULL COMMENT 'g_users.hierarchySpecialAccessZc' AFTER referred_by,
  ADD COLUMN hierarchy_special_access_cd text DEFAULT NULL COMMENT 'g_users.hierarchySpecialAccessCd',
  ADD COLUMN system_key_lead_linker varchar(50) DEFAULT NULL COMMENT 'g_users.systemKeyLeadLinker',
  ADD COLUMN media_id_media varchar(100) DEFAULT NULL COMMENT 'g_users.mediaIdMedia',
  ADD COLUMN shift varchar(50) DEFAULT NULL COMMENT 'g_users.shift',
  ADD COLUMN address text DEFAULT NULL COMMENT 'g_users.Address',
  ADD COLUMN profile_show_role tinyint(1) DEFAULT NULL COMMENT 'g_users.profileShowRole',
  ADD COLUMN profile_show_hr tinyint(1) DEFAULT NULL COMMENT 'g_users.profileShowHr',
  ADD COLUMN profile_show_comp tinyint(1) DEFAULT NULL COMMENT 'g_users.profileShowComp',
  ADD COLUMN charts_hide_visuals_1 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsHideVisuals1',
  ADD COLUMN charts_hide_visuals_2 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsHideVisuals2',
  ADD COLUMN charts_hide_visuals_3 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsHideVisuals3',
  ADD COLUMN charts_hide_visuals_4 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsHideVisuals4',
  ADD COLUMN charts_show_visuals_1 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsShowVisuals1',
  ADD COLUMN charts_show_visuals_2 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsShowVisuals2',
  ADD COLUMN charts_show_visuals_3 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsShowVisuals3',
  ADD COLUMN charts_show_visuals_4 tinyint(1) DEFAULT NULL COMMENT 'g_users.chartsShowVisuals4',
  ADD COLUMN intake_panel_stepper int DEFAULT NULL COMMENT 'g_users.intakePanelIntakePanelStepper',
  ADD COLUMN intake_panel_view_intake tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewIntakeSection',
  ADD COLUMN intake_panel_view_demo tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewDemoSection',
  ADD COLUMN intake_panel_view_insurance tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewInsuranceSection',
  ADD COLUMN intake_panel_view_tx tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewTxSection',
  ADD COLUMN intake_panel_view_atty tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewAttySection',
  ADD COLUMN intake_panel_view_inj_and_dam tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewInjAndDamSection',
  ADD COLUMN intake_panel_view_questionnaire tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewQuestionnaireSection',
  ADD COLUMN intake_panel_view_psngr tinyint(1) DEFAULT NULL COMMENT 'g_users.intakePanelViewPsngrSection',
  ADD COLUMN agreed_to_tc tinyint(1) DEFAULT NULL COMMENT 'g_users.agreedtoT&C',
  ADD COLUMN signed_to_tc text DEFAULT NULL COMMENT 'g_users.signedtoT&C (URL firma)',
  ADD COLUMN tc_agreed_at datetime DEFAULT NULL COMMENT 'g_users.T&CTimestamp';
